name: Validate TCPD (direct)

on: push

jobs:
  tcpd-ubuntu:
    name: check TCPD
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install build-essential
        shell: bash

      - name: Install Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ensure clean
        run: make clean
        shell: bash

      - name: Build and verify
        run: make test
        shell: bash
